#+options: ':t toc:nil num:nil
#+latex_header: \hypersetup{colorlinks=true}
#+latex_header: \renewcommand{\labelenumi}{\textbf{(\alph{enumi})}}
#+html_head: <style>ol { list-style-type: lower-alpha; }</style>
#+latex_header: \DeclareMathOperator{\card}{card}
#+html_head: \( \DeclareMathOperator{\card}{card} \)
#+latex_header: \newcommand\set[1]{\left\{#1\right\}}
#+html_head: \( \newcommand\set[1]{\left\{#1\right\}} \)
#+latex_header: \newcommand\Card[1]{\left|#1\right|}
#+html_head: \( \newcommand\Card[1]{\left|#1\right|} \)
#+title: Combinatorics Through Guided Discovery
#+subtitle: Chapter 1

* ยง1.2 Basic Counting Principles

** Problem 1
Label the schools "Team 1"\ldots"Team 5." Team 1 has to play Teams 2, 3, 4, and
5 (4 games); Team 2 already played Team 1 but still has to play Teams 3, 4, and
5 (3 games); \ldots; Team 4 already played Teams 1, 2, and 3 but still has to
play Team 5 (1 game); and Team 5 has already played every other team. Thus the
total number of games is for $n=5$ teams is

\begin{equation}
  \sum_{i=1}^5 (n-i) = 4 + 3 + 2 + 1 + 0 = 10.
\end{equation}

** Problem 2
a. Team 1 has to play in $n - 1$ games.
b. Team 2 has to play in $n - 2$ games.
c. Team $i$ has to play in $n - i$ games.
d. As in Problem 1, for $n$ teams

   \begin{align}
     \sum_{i=1}^n (n-i) &= n^2 - \sum_{i=1}^n i.
     % &= (n-1) + (n-2) + \ldots + [n-(n-1)] + (n-n)
   \end{align}

   Let's check that for $n=5$, which we calculated in the previous problem:

   \begin{align*}
     \sum_{i=1}^n (n-i) &= n^2 - \sum_{i=1}^n i \\
                        &= 5^2 - \sum_{i=1}^5 \\
                        &= 25 - (1 + 2 + 3 + 4 + 5) \\
                        &= 25 - 15 = 10. \: \checkmark
   \end{align*}

** Problem 3
There are 5 kinds of filling for bread 1, 5 kinds of filling for bread 2, and 5
kinds of filling for bread 3, so there are $N_f \cdot N_b = 15$ options, where
$N_f$ is number of kinds of filling and $N_b$ is number of kinds of bread.

** Problem 4

#+begin_quote
Aside: The *cardinality* of a set is the number of elements in a set, and
[[https://en.wikipedia.org/wiki/Cardinality][according to Wikipedia]], the following notation for the cardinality of set $A$
is equivalent:

\begin{equation}
  |A| \equiv n(A) \equiv \overline{\overline{A}} \equiv \card(A) \equiv \#A
\end{equation}

[Note that \verb+\card+ is not defined in \verb+amsmath+ or \verb+amssymb+, so
you have to add \verb+\DeclareMathOperator{\card}{card}+ to your preamble.]
#+end_quote

For $\card(M) = m$ and $\card(N) = n$, the number of distinct ordered pairs
$(p, q); p \in M, q \in N$ is $m \cdot n$. In [[https://en.wikipedia.org/wiki/Set-builder_notation][set-builder notation]], we could write that
as

\begin{equation}
  \left\{p \in M,\ q \in N : R = (p,q)\right\} \Rightarrow \card(R) = m \cdot n.
\end{equation}

** Problem 5
$\#(\text{drinks}) = 5$, $\#(\text{fruit}) = 4$, and per Problem\nbsp{}3,
$\#(\text{sandwiches}) = 15$, so there are $5 \cdot 4 \cdot 15 = 300$ ways to choose
between these three items.

** Problem 6
Because the order of the ice cream scoops matters (i.e. cones are distinct for
the same flavors in different orders), we don't have to worry about double
counting. $\#(\text{ice cream flavors}) = 12$, so we have $12 \cdot 12 \cdot 12 = 1728$
possible cones. For cones with distinct flavors, each flavor chosen reduces the
options by 1, so we have $12 \cdot (12 - 1) \cdot [(12-1) - 1] = 12 \cdot 11 \cdot 10 = 1320$
possible cones.

** Problem 7

a. For $S = \{1,2\}$, $T = \{a,b\}$, $f,g,\ldots: S \to T$:

   \begin{align*}
     f(1) = a,&\ f(2) = b \\
     g(1) = b,&\ g(2) = a \\
     h(1) = a,&\ h(2) = a \\
     j(1) = b,&\ j(2) = b
   \end{align*}

   +I'm a little fuzzy about $h$ and $j$ because I'm unsure if each element of
   $T$ must have an element of $\{x \in S : f(x)\}$ pointing to it, but if that
   isn't a requirement, then $h$ and $j$ are valid.+ I feel more confident
   about $h$ and $j$ because of part\nbsp{}c where there two "inputs" mapped to three
   "outputs."

For the follwing parts of the problem, consider $S = \set{1}$; $T = \set{a,
b}$; $f, g, \ldots : S \to T$ and $S' = \set{1, 2}$; $T' = \set{a}$; $f', g',
\ldots: S' \to T'$:

\begin{align*}
  \begin{gathered}
    f(1) = a \\
    g(1) = b \\
    f'(1) = a,\; f'(2) = a.
  \end{gathered}
\end{align*}

There are two ways to write a function $f : S \to T$ and only one way to write a
function $f' : S' \to T'$.

I think in general, there are $\Card{Q}^{\Card{P}}$ ways of writing a function
$g : P \to Q$


b. [@2]For $S = \{1,2,3\}$, $T = \{a,b\}$, $f,g,\ldots: S \to T$:

   \begin{align*}
     \begin{gathered}
       f(1) = a,\ f(2) = a,\ f(3) = a \\
       g(1) = a,\ g(2) = a,\ g(3) = b \\
       h(1) = a,\ h(2) = b,\ h(3) = a \\
       j(1) = a,\ j(2) = b,\ j(3) = b \\
       k(1) = b,\ k(2) = a,\ k(3) = a \\
       m(1) = b,\ m(2) = a,\ m(3) = b \\
       p(1) = b,\ p(2) = b,\ p(3) = a \\
       q(1) = b,\ q(2) = b,\ q(3) = b \\
     \end{gathered}
   \end{align*}

   Counting the above functions, we see that there are 8 ways to write a
   function $f : S \to T$, which agrees with the earlier statement that the
   number should be $\Card{T}^{\Card{S}} = 2^3 = 8$.

c. For $S = \{a,b\}$, $T = \{1,2,3\}$, and $f,g,\ldots: S \to T$:

   \begin{align*}
     f(a)=1,\ f(b)=1 &\qquad j(a)=2,\ j(b)=1 \quad& p(a)=3,\ p(b)=1 \\
     g(a)=1,\ g(b)=2 &\qquad k(a)=2,\ k(b)=2 \quad& q(a)=3,\ q(b)=2 \\
     h(a)=1,\ h(b)=3 &\qquad m(a)=2,\ m(b)=3 \quad& r(a)=3,\ r(b)=3
   \end{align*}

   Counting the above, we see that there are 9 ways to write a function $f : S
   \to T$, which agrees with the formula $\Card{T}^{\Card{S}} = 3^2 = 9$.

d. For $\Card{S} = 3$ and $\Card{T} = 12$, there are $12^3 = 1728$ functions
   $f : S \to T$.

e. Based on problem\nbsp{}6, there are $12 \cdot 11 \cdot 10 = 1320$ one-to-one functions
   from a set of three elements to a set of 12 elements. I think the general
   formula for the number of injections, $f : S \to T$ (i.e. one-to-one
   functions) is

   \begin{equation}
     \Card{f} = \frac{\Card{T}!}{\left[\Card{T}-\Card{S}\right]!}.
   \end{equation}

f. The three ice cream scoops in Problem\nbsp{}6 represent the *domain* of the
   problem, and the ice cream flavors represent the *range*. The act of
   choosing flavors is a mapping between the scoop positions and the
   flavors. Forcing a constraint of unique flavors for each scoop transforms
   choosing into an injection/one-to-one function.
