#+options: ':t toc:nil num:nil
#+latex_header: \hypersetup{colorlinks=true}
#+latex_header: \renewcommand{\labelenumi}{\textbf{\alph{enumi})}}
#+latex_header: \DeclareMathOperator{\card}{card}
#+title: Combinatorics through Guided Discovery
#+subtitle: Chapter 1

* ยง1.2 Basic Counting Principles

** Problem 1
Label the schools "Team 1"\ldots"Team 5." Team 1 has to play Teams 2, 3, 4, and
5 (4 games); Team 2 already played Team 1 but still has to play Teams 3, 4, and
5 (3 games); \ldots; Team 4 already played Teams 1, 2, and 3 but still has to
play Team 5 (1 game); and Team 5 has already played every other team. Thus the
total number of games is for $n=5$ teams is

\begin{equation}
  \sum_{i=1}^5 (n-i) = 4 + 3 + 2 + 1 + 0 = 10.
\end{equation}

** Problem 2
1. Team 1 has to play in $n - 1$ games.
2. Team 2 has to play in $n - 2$ games.
3. Team $i$ has to play in $n - i$ games.
4. As in Problem 1, for $n$ teams

\begin{align}
  \sum_{i=1}^n (n-i) &= n^2 - \sum_{i=1}^n i.
  % &= (n-1) + (n-2) + \ldots + [n-(n-1)] + (n-n)
\end{align}

Let's check that for $n=5$, which we calculated in the previous problem:

\begin{align*}
  \sum_{i=1}^n (n-i) &= n^2 - \sum_{i=1}^n i \\
                     &= 5^2 - \sum_{i=1}^5 \\
                     &= 25 - (1 + 2 + 3 + 4 + 5) \\
                     &= 25 - 15 = 10. \: \checkmark
\end{align*}

** Problem 3
There are 5 kinds of filling for bread 1, 5 kinds of filling for bread 2, and 5
kinds of filling for bread 3, so there are $N_f \cdot N_b = 15$ options, where
$N_f$ is number of kinds of filling and $N_b$ is number of kinds of bread.

** Problem 4

#+begin_quote
Aside: The *cardinality* of a set is the number of elements in a set, and
[[https://en.wikipedia.org/wiki/Cardinality][according to Wikipedia]], the following notation for the cardinality of set $A$
is equivalent:

\begin{equation}
  |A| \equiv n(A) \equiv \bbar{A} \equiv \card(A) \equiv \#A
\end{equation}

[Note that \verb+\card+ is not defined in \verb+amsmath+ or \verb+amssymb+, so
you have to add \verb+\DeclareMathOperator{\card}{card}+ to your preamble.]
#+end_quote

For $\card(M) = m$ and $\card(N) = n$, the number of distinct ordered pairs
$(p, q); p \in M, q \in N$ is $m \cdot n$. In [[https://en.wikipedia.org/wiki/Set-builder_notation][set-builder notation]], we could write that
as

\begin{equation}
  \left\{p \in M,\ q \in N : R = (p,q)\right\} \Rightarrow \card(R) = m \cdot n.
\end{equation}
