#+options: ':t toc:nil num:nil
#+latex_header: \hypersetup{colorlinks=true}
#+latex_header: \renewcommand{\labelenumi}{\textbf{(\alph{enumi})}}
#+html_head: <style>ol { list-style-type: lower-alpha; }</style>
#+latex_header: \DeclareMathOperator{\card}{card}
#+html_head: \( \DeclareMathOperator{\card}{card} \)
#+latex_header: \newcommand\set[1]{\left\{#1\right\}}
#+html_head: \( \newcommand\set[1]{\left\{#1\right\}} \)
#+latex_header: \newcommand\Card[1]{\left|#1\right|}
#+html_head: \( \newcommand\Card[1]{\left|#1\right|} \)
#+title: Combinatorics Through Guided Discovery
#+subtitle: Chapter 1

* ยง1.2 Basic Counting Principles

** Problem 1
Label the schools "Team 1"\ldots"Team 5." Team 1 has to play Teams 2, 3, 4, and
5 (4 games); Team 2 already played Team 1 but still has to play Teams 3, 4, and
5 (3 games); \ldots; Team 4 already played Teams 1, 2, and 3 but still has to
play Team 5 (1 game); and Team 5 has already played every other team. Thus the
total number of games is for $n=5$ teams is

\begin{equation}
  \sum_{i=1}^5 (n-i) = 4 + 3 + 2 + 1 + 0 = 10.
\end{equation}

** Problem 2
a. Team 1 has to play in $n - 1$ games.
b. Team 2 has to play in $n - 2$ games.
c. Team $i$ has to play in $n - i$ games.
d. As in Problem 1, for $n$ teams

   \begin{align}
     \sum_{i=1}^n (n-i) &= n^2 - \sum_{i=1}^n i.
     % &= (n-1) + (n-2) + \ldots + [n-(n-1)] + (n-n)
   \end{align}

   Let's check that for $n=5$, which we calculated in the previous problem:

   \begin{align*}
     \sum_{i=1}^n (n-i) &= n^2 - \sum_{i=1}^n i \\
                        &= 5^2 - \sum_{i=1}^5 \\
                        &= 25 - (1 + 2 + 3 + 4 + 5) \\
                        &= 25 - 15 = 10. \: \checkmark
   \end{align*}

** Problem 3
There are 5 kinds of filling for bread 1, 5 kinds of filling for bread 2, and 5
kinds of filling for bread 3, so there are $N_f \cdot N_b = 15$ options, where
$N_f$ is number of kinds of filling and $N_b$ is number of kinds of bread.

** Problem 4

#+begin_quote
Aside: The *cardinality* of a set is the number of elements in a set, and
[[https://en.wikipedia.org/wiki/Cardinality][according to Wikipedia]], the following notation for the cardinality of set $A$
is equivalent:

\begin{equation}
  |A| \equiv n(A) \equiv \overline{\overline{A}} \equiv \card(A) \equiv \#A
\end{equation}

[Note that \verb+\card+ is not defined in \verb+amsmath+ or \verb+amssymb+, so
you have to add \verb+\DeclareMathOperator{\card}{card}+ to your preamble.]
#+end_quote

For $\card(M) = m$ and $\card(N) = n$, the number of distinct ordered pairs
$(p, q); p \in M, q \in N$ is $m \cdot n$. In [[https://en.wikipedia.org/wiki/Set-builder_notation][set-builder notation]], we could write that
as

\begin{equation}
  \left\{p \in M,\ q \in N : R = (p,q)\right\} \Rightarrow \card(R) = m \cdot n.
\end{equation}

** Problem 5
$\#(\text{drinks}) = 5$, $\#(\text{fruit}) = 4$, and per Problem\nbsp{}3,
$\#(\text{sandwiches}) = 15$, so there are $5 \cdot 4 \cdot 15 = 300$ ways to choose
between these three items.

** Problem 6
Because the order of the ice cream scoops matters (i.e. cones are distinct for
the same flavors in different orders), we don't have to worry about double
counting. $\#(\text{ice cream flavors}) = 12$, so we have $12 \cdot 12 \cdot 12 = 1728$
possible cones. For cones with distinct flavors, each flavor chosen reduces the
options by 1, so we have $12 \cdot (12 - 1) \cdot [(12-1) - 1] = 12 \cdot 11 \cdot 10 = 1320$
possible cones.
